site_name: IOT
theme:
  name: material
  features:
      - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
extra_css:
    - stylesheets/extra.css

plugins:
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: auto
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
            - custom-skip-class-name
        auto_caption: false
        caption_position: bottom
